tenants:
  hsbc:
    company_name: "HSBC"
    greeting: "Hey there, I’m Eve, speaking from HSBC Talent Acquisition Team. How may I help you?"
    flows:
      default:
        enabled_agents: ["Applications", "Onboarding"]

  walmart:
    company_name: "Walmart"
    greeting: "Thank you for calling Walmart People Services, My name is Eve. How may I help you?"
    flows:
      default:
        enabled_agents: ["Applications", "Assessments", "Onboarding"]
      lite:
        enabled_agents: ["Assessments", "Onboarding"]
  translator:
    flows:
      hindi:
        target_voice: "H8bdWZHK2OgZwTN7ponr"
        placeholder: "Hindi"
        language_code: hi
        english_voice: "xctasy8XvGp2cVO9HL9k"            # for Deepgram/ElevenLabs

      spanish:
        target_voice: "tomkxGQGz4b1kE0EM722"
        placeholder: "Spanish"
        language_code: es 
        english_voice: "xctasy8XvGp2cVO9HL9k"           # for Deepgram/ElevenLabs

