tenants:
  hsbc:
    company_name: "HSBC"
    greeting: "Hey there, I’m Eve, speaking from HSBC Talent Acquisition Team. How may I help you?"
    flows:
      default:
        enabled_agents: ["Applications", "Onboarding"]

  walmart:
    company_name: "Walmart"
    greeting: "Hey there, I’m Eve, speaking from Walmart Talent Acquisition Team. How may I help you?"
    flows:
      default:
        enabled_agents: ["Applications", "Assessments", "Onboarding"]
      lite:
        enabled_agents: ["Assessments", "Onboarding"]
  translator:
    flows:
      hindi:
        tts_voice: "H8bdWZHK2OgZwTN7ponr"
        placeholder: "Hindi"
        language_code: hi            # for Deepgram/ElevenLabs

      spanish:
        tts_voice: "kjHz50TasdqbpbfK4uaN"
        placeholder: "Spanish"
        language_code: es             # for Deepgram/ElevenLabs

  powercut:
    company_name: "Power Department Telangana"
    greeting: "Hey there, I’m Madhavi, speaking from Power Department Telangana. How may I help you?"
